### PR TITLE
Add encoding argument to mitigate exception

### PR DESCRIPTION
**Pull request by just-another-dude**
Fix for exception when reading a file as shown here:
https://stackoverflow.com/questions/42919076/python-charmap-codec-cant-decode-byte-x-in-position-y-character-maps-to-undefi

### CODE REVIEW

**Comment by micheleb** [comment]
Hi, thanks a lot for the PR! 🙏🏻 

Since I'm trying to keep this compatible with both python2.7 and python3+, I have a request for a change. Could you explicitly add a version check so that the `encoding` parameter is only used in python3?

Something like

```python
is_python2 = sys.version_info[0] == 2

def fopen(f, mode):
    return open(f, mode) if is_python2 else open(f, mode, encoding='utf-8')
```

and then replace the `open()` calls with this `fopen`?

Thanks!

**Comment by just-another-dude** [comment]
> Hi, thanks a lot for the PR! 🙏🏻
> 
> Since I'm trying to keep this compatible with both python2.7 and python3+, I have a request for a change. Could you explicitly add a version check so that the `encoding` parameter is only used in python3?
> 
> Something like
> 
> ```python
> is_python2 = sys.version_info[0] == 2
> 
> def fopen(f, mode):
>     return open(f, mode) if is_python2 else open(f, mode, encoding='utf-8')
> ```
> 
> and then replace the `open()` calls with this `fopen`?
> 
> Thanks!

Hi,
I've added two functions - one for getting the python version and one for opening the file with a similar if condition to what you showed.
The problem I've found is that the text file encoding isn't necessarily going to be utf-8 even with Python 3, so I thought of using a module such as 'chardet' to determine the encoding of an existing file, but keep utf-8 default for new files in Python 3.
Hope this is good for you, cheers!

**Comment by just-another-dude** [comment]
I did a rebase and removed the previous commit.

**Comment by micheleb** [comment]
Hi again, and sorry for the long wait!

The PR looks good, but I see that there are some leftover conflicts in the file. Could you please fix them?

I'll merge then, `chardet` looks nice, thanks again!

**Comment by just-another-dude** [comment]
> Hi again, and sorry for the long wait!
> 
> The PR looks good, but I see that there are some leftover conflicts in the file. Could you please fix them?
> 
> I'll merge then, `chardet` looks nice, thanks again!

Hi Michele,
I checked the repo and  from my side it looks good.
I suppose you are talking about what looks like the conflicts in the GUI in the "Files Changed" section but I am wondering if maybe it's just some kind of bug, because if you look at the commit in my branch (patch-1), it looks normal.

**Comment by micheleb** [comment]
I'll merge the PR and fix the conflicts in a following commit, thanks!

I think that the conflicts are really there, see your fork => https://github.com/just-another-dude/subslider/blob/patch-1/subslider.py#L278 . Maybe a `git push` that failed?

Thanks again :)

**Pull request merged**
